# meta-local/conf/layer.conf
#
# Layer configuration for meta-local

# Add this layer’s recipes to BBPATH
BBPATH .= ":${LAYERDIR}"

# Where to find recipe files
BBFILES += "${LAYERDIR}/recipes-connectivity/*/*.bbappend \
            ${LAYERDIR}/recipes-devtools/*/*.bbappend \
            ${LAYERDIR}/recipes-extended/*/*.bbappend \
            ${LAYERDIR}/recipes-kernel/*/*.bbappend"

# Define this layer’s collection and file pattern
BBFILE_COLLECTIONS += "meta-local"
BBFILE_PATTERN_meta-local = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-local = "6"

# Declare compatibility with Yocto releases you support
LAYERSERIES_COMPAT_meta-local = "wrynose"

# Declare other layers this one depends on
#LAYERDEPENDS_meta-local = "meta-virtualization"

